[package]
name = "orchestrator"
description.workspace = true
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
ctrlc = { version = "3.4", features = ["termination"] }
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "orchestrator"
path = "src/main.rs"
