[package]
name = "database"
description = "Database crate for baby sitting service"
authors = ["Level Sony"]
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.4", features = ["postgres", "r2d2", "chrono"] } # Postgres, connection pool, date-time
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] } # Enumerations pour les types de données par exemple ( parent, babysitter, agency )
rocket = { version = "0.5.1", features = ["tls", "secrets"] } # Web framework

[lib]
name = "database"
path = "src/lib.rs"