apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiddoo-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: kiddoo-platform
    environment: staging
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.discord: kiddoo-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.discord: kiddoo-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.discord: kiddoo-alerts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kiddoo
  source:
    repoURL: https://github.com/sony-level/kiddoo-platform.git
    targetRevision: release
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: kiddoo-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  revisionHistoryLimit: 5
