apiVersion: v1
kind: ConfigMap
metadata:
  name: kiddoo-config
data:
  ROCKET_LOG_LEVEL: "critical"
  RUST_LOG: "warn,tower_http=warn"
  ENVIRONMENT: "production"
  API_BASE_URL: "https://api.level-sony.cloud"
  CORS_ALLOWED_ORIGINS: "https://level-sony.cloud,https://www.level-sony.cloud"
  IDENTITY_PROXY_URL: "http://prod-identity-proxy:8001"
