apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-06-19T23:35:30Z"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-proxy
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-06-19T23:35:30Z"
