apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiddoo-secrets
  labels:
    app.kubernetes.io/part-of: kiddoo-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: kiddoo-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: kiddoo/database-url
    - secretKey: oauth-client-id
      remoteRef:
        key: kiddoo/oauth-client-id
    - secretKey: oauth-client-secret
      remoteRef:
        key: kiddoo/oauth-client-secret
    - secretKey: jwt-secret
      remoteRef:
        key: kiddoo/jwt-secret
    - secretKey: rocket-secret-key
      remoteRef:
        key: kiddoo/rocket-secret-key
    - secretKey: keycloak-url
      remoteRef:
        key: kiddoo/keycloak-url
    - secretKey: keycloak-realm
      remoteRef:
        key: kiddoo/keycloak-realm
    - secretKey: keycloak-client-id
      remoteRef:
        key: kiddoo/keycloak-client-id
    - secretKey: keycloak-client-secret
      remoteRef:
        key: kiddoo/keycloak-client-secret
    - secretKey: oauth-state
      remoteRef:
        key: kiddoo/oauth-state
