apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kiddoo-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
  - target:
      kind: Deployment
      name: api-gateway
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: identity-proxy
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: ghcr.io/sony-level/kiddoo-api-gateway
    newName: ghcr.io/sony-level/kiddoo-api-gateway
    newTag: stable
  - name: ghcr.io/sony-level/kiddoo-identity-proxy
    newName: ghcr.io/sony-level/kiddoo-identity-proxy
    newTag: stable

commonLabels:
  environment: dev
