apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiddoo-secrets
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: database-url
      remoteRef:
        key: kiddoo/dev/database-url
    - secretKey: oauth-client-id
      remoteRef:
        key: kiddoo/dev/oauth-client-id
    - secretKey: oauth-client-secret
      remoteRef:
        key: kiddoo/dev/oauth-client-secret
    - secretKey: jwt-secret
      remoteRef:
        key: kiddoo/dev/jwt-secret
    - secretKey: rocket-secret-key
      remoteRef:
        key: kiddoo/dev/rocket-secret-key
    - secretKey: keycloak-url
      remoteRef:
        key: kiddoo/dev/keycloak-url
    - secretKey: keycloak-realm
      remoteRef:
        key: kiddoo/dev/keycloak-realm
    - secretKey: keycloak-client-id
      remoteRef:
        key: kiddoo/dev/keycloak-client-id
    - secretKey: keycloak-client-secret
      remoteRef:
        key: kiddoo/dev/keycloak-client-secret
    - secretKey: oauth-state
      remoteRef:
        key: kiddoo/dev/oauth-state
