apiVersion: v1
kind: ConfigMap
metadata:
  name: kiddoo-config
data:
  ROCKET_LOG_LEVEL: "normal"
  RUST_LOG: "info,tower_http=info"
  ENVIRONMENT: "staging"
  CORS_ALLOWED_ORIGINS: "https://staging.level-sony.com"
